performancecopilot/ansible-pcp

tests/check_redis.yml
tests/tests_sanity_fullstack.yml

- Fixed a typo in filename of check_grafana_pcp
- When running fullstack test - run the pmproxy localy only
- check_redis needs to be run in a shell as it uses pipe

Minor test fixes

---

.ansible-lint
.github/workflows/tox.yml
roles/grafana/files/grafana-pcp-provisioning.yaml
roles/grafana/tasks/main.yml
scripts/lsrcollection.sh
tox.ini

If the available Grafana package installed by the role is of
version >= 7.5 we can use the plugins provisioning directory
and avoid interacting with Grafana (requiring credentials).
This is tested by the (existing) check_grafana_pcp.yml case.
Resolves Red Hat BZ #1967321

Use Grafana provisioning mechanism to enable grafana-pcp

---

roles/bpftrace/templates/bpftrace.conf.j2
roles/elasticsearch/templates/elasticsearch.conf.j2
roles/elasticsearch/templates/pcp2elasticsearch.service.j2
roles/grafana/templates/grafana-pcp-datasources.yaml.j2
roles/grafana/templates/grafana.ini.j2
roles/mssql/templates/mssql.conf.j2
roles/pcp/templates/pmcd.defaults.j2
roles/pcp/templates/pmcd.sasl2.conf.j2
roles/pcp/templates/pmie.control.j2
roles/pcp/templates/pmlogger.control.j2
roles/pcp/templates/pmlogger.defaults.j2
roles/pcp/templates/pmlogger.timers.j2
roles/pcp/templates/pmproxy.defaults.j2
roles/redis/templates/redis_5.conf.j2
roles/redis/templates/redis_6.conf.j2
roles/repository/templates/artifactory.rpms.j2
roles/spark/templates/pcp2spark.service.j2

bz#2044640
Add `{{ ansible_managed | comment }}` to the template files in
roles/*/templates except the files for .labels, .url and .debs.
Thank you for your comments in https://github.com/linux-system-roles/metrics/pull/107, @natoscott. I moved the changes to this pr.

System Roles should consistently use ansible_managed in configuration files it manages

---

roles/elasticsearch/tasks/main.yml
roles/mssql/tasks/main.yml

bz#2058655
The config files are symlinks targeting to the ones in /etc/pcp/subrole.
E.g.,
lrwxrwxrwx. ... /var/lib/pcp/pmdas/mssql/mssql.conf -> ../../../../../etc/pcp/mssql/mssql.conf
The "dest" path in the template module stores the symlink path, and the
symlink is not followed in the template module by default. That makes
the symlink a regular file, while it leaves the target intact.
Please note that bpftrace shares the similar issue, and it already has `follow: yes`.
https://github.com/performancecopilot/ansible-pcp/blob/main/roles/bpftrace/tasks/main.yml#L51

Add "follow: yes" to the template task in the mssql and elasticsearch subrole.

---

roles/pcp/README.md
roles/pcp/defaults/main.yml
roles/pcp/tasks/pmie.yml
roles/pcp/tasks/pmlogger.yml
roles/pcp/templates/pmie.controld.j2
roles/pcp/templates/pmlogger.controld.j2
roles/pcp/vars/main.yml

Sometimes its beneficial to use the all-in-one control file method
with pmie and pmlogger, rather than using separate control.d files.
This commit provides a toggle to switch on a users preferred mode.

Provide pcp_single_control option for control.d vs control files

---

roles/pcp/tasks/pmie.yml
roles/pcp/tasks/pmlogger.yml

We have an issue when we run the test playbooks in the metrics role from linux-system-role. The failed test case is to run the tests on a host where the control node and the managed node are shared. At the end of each test, the newly installed rpm packages in each test are removed and the state of services are reset. But still these tests fail:
```
tests_sanity_basic.yml
tests_sanity_fullstack.yml
tests_sanity_query.yml
tests_sanity_retention.yml
```
in `Check if primary pmie is running (metrics/tests/check_pmie.yml)` unless the pmie.service is restarted as in the diff.

pmie - when pmie is configured, restart the service if it's already up.

---

.ansible-lint
roles/elasticsearch/tasks/main.yml
roles/spark/tasks/main.yml

Instead of setting "ignore_errors" in .ansible-lint globally, put "# noqa ignore-errors" on each task with "ignore_errors: yes".

Use "#noqa ignore_errors"

---

galaxy.yml

Unfortunately, ansible-galaxy collection build includes every single file in the repository root by default. This adds `build_ignore`s for tests and other development files that cruft up the built collection artifact.
References: https://src.fedoraproject.org/rpms/ansible-pcp/pull-request/3
---
This is a modified version of the patch I submitted to the Fedora package. At some point, this should be replaced with the new [manifest directives feature](https://docs.ansible.com/ansible-core/devel/dev_guide/developing_collections_distributing.html#manifest-directives) that was added in core 2.14. Older versions of ansible will just ignore the `manifest` key if you add it to galaxy.yml (i.e. it won't break the build), but I still think we should stick to the more compatible solution.

galaxy.yml: build_ignore unnecessary files

---

roles/pcp/vars/main.yml

Related to https://github.com/linux-system-roles/metrics/pull/133

Correction to naming of recent pmieconf vfs_rules configuration

---

roles/bpftrace/templates/bpftrace.conf.j2
roles/elasticsearch/templates/elasticsearch.conf.j2
roles/elasticsearch/templates/pcp2elasticsearch.service.j2
roles/grafana/templates/grafana-pcp-datasources.yaml.j2
roles/grafana/templates/grafana_7.ini.j2
roles/grafana/templates/grafana_9.ini.j2
roles/mssql/templates/mssql.conf.j2
roles/pcp/templates/pmcd.defaults.j2
roles/pcp/templates/pmcd.sasl2.conf.j2
roles/pcp/templates/pmie.control.j2
roles/pcp/templates/pmie.controld.j2
roles/pcp/templates/pmlogger.control.j2
roles/pcp/templates/pmlogger.controld.j2
roles/pcp/templates/pmlogger.defaults.j2
roles/pcp/templates/pmlogger.timers.j2
roles/pcp/templates/pmproxy.defaults.j2
roles/redis/templates/redis_5.conf.j2
roles/redis/templates/redis_6.conf.j2
roles/repository/templates/artifactory.rpms.j2
roles/spark/templates/pcp2spark.service.j2

Add repo and role name to the generated config files.
```
```
Note: This information is provided to help customers identify that it was generated by ansible-pcp roles. It may also be used for future analysis.

 Fingerprint ansible-pcp managed config files

---

.ansible-lint
docs/bpftrace/setup.yml
docs/elasticsearch/setup.yml
docs/grafana/setup.yml
docs/mssql/basic.yml
docs/mssql/secure.yml
docs/pcp/farms.yml
docs/pcp/setup.yml
docs/pcp/users.yml
docs/postfix/basic.yml
docs/redis/setup.yml
docs/repository/setup.yml
docs/spark/setup.yml
meta/runtime.yml
tests/check_pmlogger.yml

All plays must be named
Must use `changed_when` for `command` and `shell` with `when` also
For some reason ansible-lint does not like the `required_ansible` version

fix additional ansible-lint issues

---

.ansible-lint
meta/runtime.yml

ansible-lint does not like version 2.9
Instead, use 2.11.0
Note that nothing really checks this, so we should be ok to
use 2.9 - the version only applies to ansible-core

docs: ansible-lint does not like version 2.9

---

roles/redis/README.md
roles/redis/defaults/main.yml
roles/redis/templates/redis_5.conf.j2
roles/redis/templates/redis_6.conf.j2

Adds a toggle to disable Redis' incremental save feature.
Saving the Redis database seems unnecessary for the way `pmproxy` uses it. Disabling the save feature vastly reduces the CPU and I/O utilization of Redis.
Setting `redis_save_to_disk: false` causes Redis saves to be disabled.

feat: Add a toggle to disable saving Redis database to disk

---

roles/elasticsearch/tasks/main.yml
roles/spark/tasks/main.yml

Use /etc/systemd/system instead of /usr/lib/systemd/system
for the elasticsearch service file on ostree systems.

fix: ostree systems cannot write to /usr; use /etc instead

---

.github/dependabot.yml
.github/workflows/ansible-lint.yml
meta/runtime.yml
roles/bpftrace/tasks/main.yml
roles/elasticsearch/tasks/main.yml
roles/grafana/tasks/main.yml
roles/mssql/tasks/main.yml
roles/pcp/tasks/pmcd.yml
roles/pcp/tasks/pmie.yml
roles/pcp/tasks/pmlogger.yml
roles/pcp/tasks/pmproxy.yml
roles/redis/tasks/main.yml
roles/repository/tasks/main.yml
roles/spark/tasks/main.yml
scripts/lsrcollection.sh

Use the latest supported ansible-lint github action which requires
conversion to collection.
Add dependabot checking for latest versions of github actions
Use `mode: "0NNN"` instead of `mode: 0NNN`.
ansible-test requires supported version `>= 2.13.0` even though the code
still supports earlier versions of ansible.

ci: use latest version of ansible-lint 2.16; fix lint issues

---

roles/repository/tasks/main.yml

Enhancement:
The PCP store has moved from Artifactory to Packagecloud. This has been reflected in name of templates of `repository` role, however it has not been reflected in the main task of the `repository` role.
This commit fixes the main task of the `repository` role to use Packagecloud templates.

fix: Use of correct template in repository role

---

roles/redis/tasks/main.yml
roles/redis/vars/Fedora.yml
roles/redis/vars/Fedora_x86_64.yml

Non x86_64 builds of Redis do not support the RediSearch extension on Fedora distro. As such, use of the redis sub-role fails on non x86_64 architectures as the RediSearch is enforced on all architectures supported by Fedora.
This fix allows use of the RediSearch extension on Fedora distro, only when run on x86_64 architecture.
@richm can you please review this pull request ? There might be a better way how to achieve the required outcome and you are more experienced.

fix: Do not load RediSearch on non x86_64 Fedoras

---

tests/restore_services_state.yml

Some services might not be installed (i.e. redis) if a relevant subrole is not used (i.e. performancecopilot.metrics.redis). Thus an attempt to restore such a service fails. This commit adds a check for the service presence before its restoration.

fix: do not restore non-installed services

---

.github/workflows/ansible-lint.yml
roles/bpftrace/meta/main.yml
roles/elasticsearch/meta/main.yml
roles/grafana/meta/main.yml
roles/mssql/meta/main.yml
roles/pcp/meta/main.yml
roles/postfix/meta/main.yml
roles/redis/meta/main.yml
roles/repository/meta/main.yml
roles/spark/meta/main.yml

According to the Ansible team, support for listing platforms in
role `meta/main.yml` files is being removed.
Instead, they recommend using `galaxy_tags`
https://github.com/ansible/ansible/blob/stable-2.17/changelogs/CHANGELOG-v2.17.rst
"Remove the galaxy_info field platforms from the role templates"
https://github.com/ansible/ansible/issues/82453
Many roles already have tags such as "rhel", "redhat", "centos", and "fedora".
I propose that we ensure all of the system roles have these tags.
Some of our roles support Suse, Debian, Ubuntu, and others.
We should add tags for those e.g. the ssh role already has tags for "debian" and "ubuntu".
In addition - for each version listed under `platforms.EL` - add a tag like `elN`.
Q: Why not use a delimiter between the platform and the version e.g. …

fix: add support for EL10

---

.github/workflows/pr-title-lint.yml

In accordance with
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
Use an env var for the PR title in the checker
Rename the action because it only checks the PR title, not the
commits.

ci: use env var for PR title; rename to pr-title-lint

---

roles/redis/tasks/main.yml

`ansible_facts['ansible_architecture']` replaced with `ansible_facts['architecture']`

fix: Fixed usage of architecture in the redis sub-role

---

roles/pcp/tasks/pmie.yml

When a file does not exist, the item.found in
__pcp_global_webhook_action_status does not need to be defined. This commit handle such a situation.

fix: Handle undefined item in pmie configuration

---

.ansible-lint
.github/workflows/markdownlint.yml
.markdownlint.yaml
README.md
plugins/README.md
roles/elasticsearch/README.md
roles/keyserver/README.md
roles/mssql/README.md
roles/pcp/README.md
roles/spark/README.md

Enhancement: Add markdownlint GH workflow and config file to check all .md files
Reason: Ensure that all markdown files have correct syntax and will be build correctly.

ci: Add markdownlint GH workflow

---

roles/keyserver/vars/CentOS_6.yml
roles/keyserver/vars/CentOS_7.yml
roles/keyserver/vars/CentOS_8.yml
roles/keyserver/vars/CentOS_9.yml

A fallthrough was accidentally picking up valkey package name for these older RHEL releases - that's correct for Fedora and RHEL-10 onward, but not earlier RHEL releases.

fix: older versions of Centos (pre-10) need to use redis package

---

roles/grafana/templates/grafana_9.ini.j2

I think this line is supposed to use `{{ __grafana_keyserver_datasource_alttype }}`
like the grafana_7.ini.j2 template.  At any rate,
`{{ performancecopilot-valkey-datasource }}` is not a variable, and not even a
valid variable name (cannot have `-` in a variable name.

fix: use __grafana_keyserver_datasource_type variable instead of its string value

---

tests/check_keyserver.yml
tests/restore_services_state.yml
tests/tests_verify_auth.yml
tests/tests_verify_basic.yml
tests/tests_verify_bpftrace.yml
tests/tests_verify_from_elasticsearch.yml
tests/tests_verify_grafana.yml
tests/tests_verify_into_elasticsearch.yml
tests/tests_verify_mssql.yml
tests/tests_verify_pmie_webhook.yml
tests/tests_verify_postfix.yml
tests/tests_verify_repository.yml
tests/tests_verify_retention.yml
tests/tests_verify_spark.yml

Enhancement:
Reason:
Result:
Issue Tracker Tickets (Jira or BZ if any):

fix: testsuite using __keyserver_name properly

---

docs/pcp/setup.yml
roles/pcp/README.md
roles/spark/tasks/main.yml
roles/spark/vars/CentOS_7.yml
roles/spark/vars/RedHat_7.yml

There is no pcp-pmda-openmetrics package on EL7, so ensure
the spark role works in that case.

fix: no pcp-pmda-openmetrics on EL7

---

.ansible-lint
tests/tests_verify_fullstack.yml

Latest ansiblelint complains about
> Error: Task name 'Check headers for ansible_managed, fingerprint' is
> not unique. It was first used on line 72.
----
Fixes [this failure](https://github.com/linux-system-roles/metrics/actions/runs/15830115696/job/44620413064?pr=243#step:6:257). I'll also push it to https://github.com/linux-system-roles/metrics/pull/243 to verify.

tests: Unique task names; ignore downloaded collections for ansible-lint
